//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Admission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_registration
    {
        public int r_id { get; set; }
        public string r_email { get; set; }
        public string r_cnic { get; set; }
        public string r_password { get; set; }
        public string r_fullname { get; set; }
        public string r_mobile { get; set; }
        public System.DateTime r_date { get; set; }
        public string r_image { get; set; }
    }
}
