//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Admission.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class online_admissionEntities7 : DbContext
    {
        public online_admissionEntities7()
            : base("name=online_admissionEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_registration> admin_registration { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<Merit> Merits { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<student_registration> student_registration { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
