//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_Admission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_registration()
        {
            this.Merits = new HashSet<Merit>();
        }
    
        public int r_id { get; set; }
        public string r_cnic { get; set; }
        public string r_password { get; set; }
        public string r_fullname { get; set; }
        public string r_fathername { get; set; }
        public string r_mobile { get; set; }
        public string r_phone { get; set; }
        public double r_hsc_gpa { get; set; }
        public double r_ssc_gpa { get; set; }
        public int r_status { get; set; }
        public System.DateTime r_date { get; set; }
        public string r_image { get; set; }
        public int r_p1 { get; set; }
        public int r_p2 { get; set; }
        public int r_p3 { get; set; }
        public int r_cat { get; set; }
        public string SSC_marksheet { get; set; }
        public string HSC_marksheet { get; set; }
    
        public virtual category category { get; set; }
        public virtual department department { get; set; }
        public virtual department department1 { get; set; }
        public virtual department department2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merit> Merits { get; set; }
    }
}
